name: EleutherAI/gpt-j-6B

### for WISE Start ###
hidden_act: ''
mask_ratio: 0.2
edit_lr: 1.0
n_iter: 70
norm_constraint: 1.0
act_margin: [15.0, 40.0, 20.0] # alpha, beta, gamma
alpha: 15.0
beta: 40.0
gamma: 20.0
act_ratio: 0.88
save_freq: 500
merge_freq: 1000
merge_alg: 'ties'
objective_optimization: 'only_label'
inner_params:
- transformer.h[21].mlp.fc_out.weight


## alternative: WISE-Merge, WISE-Retrieve

# for merge (if merge)
densities: 0.53
weights: 1.0

# for retrieve (if retrieve, pls set to True)
retrieve: False
replay: False # True --> will replay the past editing instances: see https://arxiv.org/abs/2405.14768 Appendix B.3

model_parallel: False
### for WISE End ###

#### for LTI start ####
mid_kl_factor: 0.0425
last_kl_factor: 0.0625
nll_factor: 1
midlayers:
  - 15
constr_pos: subject
#### for LTI end ####

fact_token: subject_last

clamp_norm_factor: 0.75
v_num_grad_steps: 25
v_lr: 0.5
v_loss_layer: 27
v_weight_decay: 0.5
kl_factor: 0.0625

layers:
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
mom2_update_weight:
  - 15000
  - 15000
  - 15000
  - 15000
  - 15000
  - 15000
layer_selection: all

rewrite_module_tmp: transformer.h.{}.mlp.fc_out
layer_module_tmp: transformer.h.{}
mlp_module_tmp: transformer.h.{}.mlp
attn_module_tmp: transformer.h.{}.attn
ln_f_module: transformer.ln_f
lm_head_module: lm_head

mom2_dataset: wikipedia
mom2_n_samples: 100000
mom2_dtype: float32
mom2_adjustment: true
mom2_maxseqlen:







